<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvxgxcj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvxgxcj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWvxgxcj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWvxgxcj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWvxgxcj\appProdProjectContainer([
    'container.build_hash' => 'Wvxgxcj',
    'container.build_id' => '5712e457',
    'container.build_time' => 1607587207,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvxgxcj');
